export type { Article, Broadcast, BroadcastScript } from "@techmato/types";
export { extractArticleContent, extractFullContent } from "./extract/extract.js";
export type { ScriptError } from "./script/script.js";
export { generateScript } from "./script/script.js";
export type { SelectError, Selection } from "./select/select.js";
export { selectArticles } from "./select/select.js";
export { fetchAllSources, fetchSourceArticles } from "./sources/fetch.js";
export type { NewsSource } from "./sources/registry.js";
export { SOURCES } from "./sources/registry.js";
export type { TtsCue, TtsCueKind, TtsError, TtsManifest, TtsOptions } from "./tts/tts.js";
export { synthesizeScript } from "./tts/tts.js";
